### ISSUE TITLE
Build failing for crDroid

### ISSUE THREAD

**Issue by jensgrunzer1** [zircon-development/android_device_xiaomi_zircon#1]
I am currently trying to build the crDroid rom using the devicetrees and kernelfiles from this organisation. But i am encountering the 
following [error](https://pastebin.com/BJfU5pRX) when running `brunch zircon`. This error seem to be occuring because the file `vendor/xiaomi/zircon-firmware/common/common-vendor.mk` does not exist. I ran the extract-files.py script which ran without errors but it extracted the vendor files the `vendor/xiaomi/zircon` folder. Where can i get the required files?

**Comment by jensgrunzer1** [comment]
I just removed the line that required this directory and building seems to be going fine

**Comment by AdarshGrewal** [comment]
https://git.mainlining.org/zircon-development
 I would recommend using the vendor repos from here,anyways issues is not for build errors XD
